### PR TITLE
Allow for builds on Win8x64/VS2012

### PR DESCRIPTION
**Pull request by neiz**
Removed reference to System.Management.Automation and located newer
version to allow for successful build.  Removed 'Wish' project as Visual Studio setup projects (vdproj) are depreciated in VS2012.  Assuming will need migration to WiX

### CODE REVIEW

**Comment by davidebbo** [comment]
I tried a clean build and it failed for me starting with:

```
d:\Code\GitHub\Wish\Wish.Commands\bin\Debug\Wish.Commands.dll : error CS1705: Assembly 'Wish.Commands, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Management.Automation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\Code\GitHub\Wish\Wish.Commands.Tests\Wish.Commands.Tests.csproj]
```

Something I'm doing wrong?

**Comment by neiz** [comment]
Please try the commit I just added - I had forgot to clean project so some ref's were still out of whack

**Comment by davidebbo** [comment]
Yep, it builds clean now!

**Comment by neiz** [comment]
Cool :)

**Comment by tltjr** [comment]
Looks great! Thanks.

**Pull request merged**
